### ISSUE TITLE
Support more than one source

### ISSUE THREAD

**Issue by htdat** [htdat/currency-conversion#5]
## Tasks for v1

- [x] Build Settings component 
- [x] Update canFetchData() helper to handle 
 
###  Sources: 

- https://api.exchangeratesapi.io/latest - only 32 currencies - no key 
- https://api.exchangerate-api.com/v5/latest - only 51 currencies - no key  - https://www.exchangerate-api.com/docs/free-exchange-rate-api
- https://docs.openexchangerates.org/docs/supported-currencies - free - 170 currencies - key required - https://openexchangerates.org/api/latest.json?app_id=xxxxxx

## To-do for v2

Not yet implement two followings sources: 

- [ ] https://fixer.io/ - free - 170 currencies - key required - base current is always EUR for free plans while current code can support USD as base only. 
- [ ] https://currencylayer.com/product  - free - 84 currencies - key required. - the JSON response does not save exchange rates in `rates` key while the currency code checks this object key to verify data.

**Comment by htdat** [comment]
Closing! 3 sources are quite enough for now.
